# Generated by Django 2.2.16 on 2022-11-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_change_field_pub_date_in_models_post_and_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='pub_date',
        ),
    ]
